name: Update Model Metrics

on:
  push:
  schedule:
    - cron: "16 * * * *"

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Cache playwright assets
        uses: actions/cache@v5
        id: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-v1
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install chromium via Playwright
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install chromium

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"

      - name: Run model metrics
        timeout-minutes: 30
        run: uv run model-metrics.py
        env:
          CRAWLEE_LOG_LEVEL: DEBUG

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@user.noreply.github.com"
          git config --local user.name "Archive"

          # Prevent conflicts due to changes being made while workflow is
          # running. This workflow can take a while, so it's prudent to pull
          # before commit anything new.
          git pull --rebase --autostash

          git add model-metrics.json
          git commit -m "Metrics from $(date -u)" || exit 0
          git push
